### ISSUE TITLE
Print with IE or Edge

### ISSUE THREAD

**Issue by GoAndDoIt** [j26design/PDF-Embedder-Premium#11]
Hello, we have your PDF widget version 1 for Muse. The print button works only with Chrome and FireFox, with IE or Edge only the top half of the pages are printed.
I found several blogs entries related to similar problems, all linked to the zoom level or PRINT_OUTPUT_SCALE dependencies. But I did not find an applicable solution for your widget
Help !!!
Many thanks, Best regards, Jean

**Comment by jp26jp** [comment]
Okay, I see how to fix the issue. I just have to make sure everything works with version 2 and then I'll update the files.

**Comment by jp26jp** [comment]
BTW, I appreciate you adding that the info you found was based around `PRINT_OUTPUT_SCALE`. That made identifying the issue much faster.

**Comment by GoAndDoIt** [comment]
Hello, Will your solution be on version 1 of the widget ?
Thanks for your help

**Comment by jp26jp** [comment]
Yes, but using version 2 will be better. Especially since it's a free upgrade.

**Comment by GoAndDoIt** [comment]
OK, fine, Could you please inform me as soon as the problem is solved
Thanks for your help

**Comment by GoAndDoIt** [comment]
Hello, do you have any news ?

**Comment by GoAndDoIt** [comment]
Hello, any news ? 
Do you have a corrected widget ?
Thanks for your help

**Comment by jp26jp** [comment]
The update that was sent out today fixes this issue!

**Comment by GoAndDoIt** [comment]
Hello,

Many thanks for the update

I just got the new files and run a test, unfortunately it does not solve the problem

Here with a screen copy showing the printout stops at 50% of the page

 

 


	
		


Many thanks for your help

Best regards

Jean

 

 

 

De : John R Perry [mailto:notifications@github.com] 
Envoyé : mercredi 15 février 2017 21:11
À : j26design/PDF-Embedder-Premium <PDF-Embedder-Premium@noreply.github.com>
Cc : GoAndDoIt <j_kubler@club-internet.fr>; State change <state_change@noreply.github.com>
Objet : Re: [j26design/PDF-Embedder-Premium] Print with IE or Edge (#11)

 

The update that was sent out today fixes this issue!

**Comment by jp26jp** [comment]
I hate IE. [I let them know](https://github.com/mozilla/pdf.js/issues/3983). I'll let you know if there's an update.

**Comment by jp26jp** [comment]
Okay, this was definitely fixed in the latest update. Just redownload the files that were sent in the last update email.

**Comment by GoAndDoIt** [comment]
Hello,

 

Thanks for this new version

But I am very disappointed, It’s still the same problem.

My little test site is on bisinesscatalyst, how could I help you debugging and or analyse to find the problem ?

During file transfer to my test site, I found no difference in /web and /build files between version 2.1.0 and 2.2.0 (they are all the same files)

 

Thanks for your help

Best regards

Jean

 

De : John R Perry [mailto:notifications@github.com] 
Envoyé : dimanche 19 février 2017 01:10
À : j26design/PDF-Embedder-Premium <PDF-Embedder-Premium@noreply.github.com>
Cc : GoAndDoIt <j_kubler@club-internet.fr>; State change <state_change@noreply.github.com>
Objet : Re: [j26design/PDF-Embedder-Premium] Print with IE or Edge (#11)

 

Okay, this was definitely fixed in the latest update. Just redownload the files that were sent in the last update email.

**Comment by jp26jp** [comment]
Sorry you're so disappointed. The issue is fixed. I tested it repeatedly. Start the process over again. Here's an example of it working pdfwhite.businesscatalyst.com

**Comment by GoAndDoIt** [comment]
Hello,

Thanks, please could you setup your test with paper size = A4 (21cm x 29,7cm) , then the problem happend

 

Thanks for your help

Best regards

Jean

 

De : John R Perry [mailto:notifications@github.com] 
Envoyé : dimanche 19 février 2017 19:01
À : j26design/PDF-Embedder-Premium <PDF-Embedder-Premium@noreply.github.com>
Cc : GoAndDoIt <j_kubler@club-internet.fr>; State change <state_change@noreply.github.com>
Objet : Re: [j26design/PDF-Embedder-Premium] Print with IE or Edge (#11)

 

Sorry you're so disappointed. The issue is fixed. I tested it repeatedly. Start the process over again. Here's an example of it working pdfwhite.businesscatalyst.com

**Comment by GoAndDoIt** [comment]
Hello,

 

I reloaded completely my tests site, same problem

Please could you try : http://hebenoui.businesscatalyst.com/

 

Many thanks for your help

Best regards

Jean

 

De : John R Perry [mailto:notifications@github.com] 
Envoyé : dimanche 19 février 2017 19:01
À : j26design/PDF-Embedder-Premium <PDF-Embedder-Premium@noreply.github.com>
Cc : GoAndDoIt <j_kubler@club-internet.fr>; State change <state_change@noreply.github.com>
Objet : Re: [j26design/PDF-Embedder-Premium] Print with IE or Edge (#11)

 

Sorry you're so disappointed. The issue is fixed. I tested it repeatedly. Start the process over again. Here's an example of it working pdfwhite.businesscatalyst.com
